#!/usr/bin/env ruby

# Suggest loose tracks which might have duplicates elsewhere in the
# tree. Output has escaped line endings for pasting straight into
# mplayer for comparison.

require 'pathname'

abort 'usage: duplicate_tracks <directory>' unless ARGV.size == 1

BASE = Pathname.new(ARGV.first)

IN_ALBUMS = BASE.find.reject { |f| f.to_s.include?('/tracks/') }.map do |t|
  [t.basename.to_s[3..-1], t.to_s]
end.to_h

(BASE + 'tracks').children.each do |t|
  track = t.basename.to_s
  puts format("%s \\\n  %s\n\n", t, IN_ALBUMS[track]) if IN_ALBUMS[track]
end
