#!/usr/bin/env ruby

# Print a list of albums I have as MP3s but not as FLACs

require 'pathname'

def albums(path)
  Pathname.new(path)
          .find
          .select { |f| f.directory? }
          .map(&:basename).to_a
end

(albums('/storage/mp3/albums') - albums('/storage/flac/albums')).each do |a|
  puts a
end
