#!/bin/ksh

# Find files with missing tags. Requires aud.
# Usage: first argument is an optional directory.

if (( $# != 1 ))
then
	print -u2 "usage: ${0##*/} <directory>"
	exit 1
fi

BASE=$1

# SCRIPT STARTS HERE

# If we don't have an argument, default to the BASE

[[ -n $1 ]] && DIR=$1 || DIR=$BASE

find $DIR -type d | sort | while read dir
do
	[[ $(ls -l $dir | grep -c "^-.*flac$") == 0 ]] && continue

	# Look at the files in this directory and see if they're missing any
	# tags. We report a directory has missing tags if ANY of the files
	# are.

	find $dir -name \*.flac | while read file
	do
		MISSING=""

		aud info $file | grep " : " | while read key sep value
		do
			[[ $key == "filename" ]] && continue
			[[ -z $value ]] && MISSING="$MISSING $key"
		done
	done

	if [[ -n $MISSING ]]
	then
		print "\n${dir##*/}"

		for tag in $MISSING
		do
			print "  $tag"
		done
	fi
done
