#!/bin/ksh

# Find 24-bit albums and symlink them into a common directory, to try to see
# whether hi-res sounds any different. (It doesn't.)
# Requires aud

if (( $# != 1 ))
then
	print -u2 "usage: ${0##*/} <directory>"
	exit 1
fi

LINKDIR="${1}/24-bit"

if test -d $LINKDIR
then
	rm ${LINKDIR}/*
else
	mkdir -p $LINKDIR
fi

find ${1}/albums ${1}/eps -type d | while read d
do
	# See if the first file in there is 24-bit. If it is, assume everything
	# else is. Crude, but it'll do

	if aud info $(ls $d/*flac 2>/dev/null | sed 1q) | egrep -s "Bitrate : 24"
	then
		print "$d is 24-bit"
		ln -s $d $LINKDIR
	fi
done
