#!/usr/bin/env ruby
# frozen_string_literal: true

# rip_cd can't handle various artist albums if they're ripped using
# CD-TEXT. This may fix the broken names.

require 'pathname'
require 'fileutils'

Pathname.new(__dir__).children.each do |f|
  next unless f.extname == '.flac'

  chunks = f.basename.to_s.split('.')
  number = chunks.first

  title, artist = chunks[2].chomp('_by_various').split('_from_')

  FileUtils.mv(f,
               f.dirname + format('%s.%s.%s.flac', number, artist, title))
end
